version: "2.0"

services:
  web:
    image: sinatra-app:latest
    env_file: .env
    depends_on:
      - redis
    ports:
      - "19292:9292"
    links:
      - redis:redis
    command: bundle exec puma -p $APP_PORT
  redis:
    image: "redis:alpine"
