version: '2'
services:
  web:
    image: sinatra-app:latest
    environment:
      - APP_HOME=/app
      - RACK_ENV=production
      - PORT=9292
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    command: bundle exec puma -p ${PORT}
    ports:
      - "19292:9292"
    links:
      - redis:redis
  redis:
    image: "redis:alpine"
