---
version: "3.6"
services:
  web:
    image: jjuarez/docker-sinatra-app:latest
    env_file: .env
    depends_on:
      - redis
    ports:
      - "4567:4567"
  redis:
    image: "redis:6.0.8-alpine"
    ports:
      - "6379:6379"
